services:
  app:
    image: ms-product:v1
    container_name: ms-product
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db-product
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: admin
    networks:
      - ms-network
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres-product
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db-product
    networks:
      - ms-network

networks:
  ms-network:
    driver: bridge